name: CI
on: [push]
env:
  JAVA_VERSION: 8
  NODE_VERSION: 12
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        id: gradle-npm-cache
        with:
          path: |
            ~/.n*
            ~/.m2
            ~/.gradle
            !~/.gradle/exclude
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', '**/package-lock.json', '**/*.gradle', '**/*.properties') }}
      - run: ./gradlew -p docs npm_run_ci
      - name: Deploy 🚀 GitHub Pages build
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/src/.vuepress/dist # The folder the action should deploy.
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.n*
            ~/.m2
            ~/.gradle
            !~/.gradle/exclude
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', '**/package-lock.json', '**/*.gradle', '**/*.properties') }}
      - run: npm install -g wait-port
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./gradlew -p server ; ./gradlew -p client
      - run: |
          java -Dfile.encoding="UTF-8" -jar $GITHUB_WORKSPACE/server/build/libs/*.jar &
          echo wait-port 7070...
          sleep 5s
          java -Dfile.encoding="UTF-8" -jar $GITHUB_WORKSPACE/client/build/libs/*.jar
